import { EProductStatus, type IProduct } from './type';
const now = new Date();
export const listProducts: IProduct[] = [
  {
    id: '1',
    name: 'Kaos Distro Vintage',
    price: '50000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 20,
  },
  {
    id: '2',
    name: 'Sweater Pria',
    price: '70000',
    status: EProductStatus.UNAVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 0,
  },
  {
    id: '3',
    name: 'Jamur Crispy',
    price: '10000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 60,
  },
  {
    id: '4',
    name: 'Pashmina Kaos Rayon Premium',
    price: '25000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 89,
  },
  {
    id: '5',
    name: 'Kopi Arabika Gayo',
    price: '35000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'drink', created_at: now, updated_at: now, products: [] },
    stock: 120,
  },
  {
    id: '6',
    name: 'Celana Jeans Slim Fit',
    price: '120000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 35,
  },
  {
    id: '7',
    name: 'Keripik Singkong Balado',
    price: '15000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 90,
  },
  {
    id: '8',
    name: 'Hoodie Polos Fleece',
    price: '90000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 50,
  },
  {
    id: '9',
    name: 'Teh Hijau Organik',
    price: '28000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'drink', created_at: now, updated_at: now, products: [] },
    stock: 75,
  },
  {
    id: '10',
    name: 'Topi Baseball Keren',
    price: '40000',
    status: EProductStatus.UNAVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 0,
  },
  {
    id: '11',
    name: 'Roti Gandum Utuh',
    price: '20000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 40,
  },
  {
    id: '12',
    name: 'Dress Wanita Motif Bunga',
    price: '150000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 15,
  },
  {
    id: '13',
    name: 'Susu UHT Full Cream',
    price: '18000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'drink', created_at: now, updated_at: now, products: [] },
    stock: 100,
  },
  {
    id: '14',
    name: 'Dompet Kulit Asli',
    price: '80000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'jewelery', created_at: now, updated_at: now, products: [] },
    stock: 25,
  },
  {
    id: '15',
    name: 'Coklat Batangan Premium',
    price: '22000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 65,
  },
  {
    id: '16',
    name: 'Kemeja Flanel Pria',
    price: '110000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 30,
  },
  {
    id: '17',
    name: 'Biskuit Aneka Rasa',
    price: '9000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 150,
  },
  {
    id: '18',
    name: 'Rok Plisket Panjang',
    price: '65000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 45,
  },
  {
    id: '19',
    name: 'Minyak Goreng Sawit',
    price: '24000',
    status: EProductStatus.UNAVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 0,
  },
  {
    id: '20',
    name: 'Sepatu Sneakers Pria',
    price: '250000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 10,
  },
  {
    id: '21',
    name: 'Mie Instan Kuah Soto',
    price: '3000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 200,
  },
  {
    id: '22',
    name: "Gamis Syar'i Modern",
    price: '180000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 8,
  },
  {
    id: '23',
    name: 'Kerupuk Udang Enak',
    price: '12000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 110,
  },
  {
    id: '24',
    name: 'Gelang Emas Simpel',
    price: '300000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'jewelery', created_at: now, updated_at: now, products: [] },
    stock: 5,
  },
  {
    id: '25',
    name: 'Sirup Cocopandan',
    price: '26000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'drink', created_at: now, updated_at: now, products: [] },
    stock: 70,
  },
  {
    id: '26',
    name: 'Tas Ransel Laptop',
    price: '130000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 22,
  },
  {
    id: '27',
    name: 'Permen Rasa Buah',
    price: '5000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 300,
  },
  {
    id: '28',
    name: 'Sandangan Pantai Unisex',
    price: '55000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'clothing', created_at: now, updated_at: now, products: [] },
    stock: 40,
  },
  {
    id: '29',
    name: 'Frozen Food Nugget Ayam',
    price: '45000',
    status: EProductStatus.UNAVAILABLE,
    category: { id: '1', name: 'food', created_at: now, updated_at: now, products: [] },
    stock: 0,
  },
  {
    id: '30',
    name: 'Kacamata Hitam Stylish',
    price: '75000',
    status: EProductStatus.AVAILABLE,
    category: { id: '1', name: 'jewelery', created_at: now, updated_at: now, products: [] },
    stock: 18,
  },
];
